# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestFirstdemo():
    def setup_method(self, method):
        # 实例化 chromedriver
        self.driver = webdriver.Chrome()
        self.vars = {}
        # 统一设置隐式等待
        self.driver.implicitly_wait(1)

    def teardown_method(self, method):
        # 关闭 driver 回收资源
        self.driver.quit()

    def test_firstdemo(self):
        # 测试步骤
        # 打开web页面
        self.driver.get("https://ceshiren.com/")
        # 修改浏览器窗口分辨率
        self.driver.set_window_size(739, 816)
        # 点击搜索按钮
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-search").click()
        # 定位输入框元素,输入内容
        self.driver.find_element(By.ID, "search-term").send_keys("selenium")
        # 按下Enter按钮
        self.driver.find_element(By.ID, "search-term").send_keys(Keys.ENTER)
        # 断言搜索是否正确
        # assert self.driver.find_element(By.CSS_SELECTOR,
        #                                 ".item:nth-child(1) .topic .search-highlight:nth-child(1)").text == "selenium"
        assert self.driver.find_element(By.XPATH,
                                 '//*[@id="ember6"]/header/div/div/div[2]/div/div/div/div/div[2]/div/ul/li[1]/a/span[1]/span[1]/span[2]/span/span[1]').text == "selenium"
        # 查看界面展示
        time.sleep(5)
